spring: 
  application: 
    name: ${TENANT_GROUP:vanke-scpg-pluto}
  http: 
    multipart: 
      enabled: true
      file-size-threshold: 0
      location: ./tmp
      max-file-size: 10MB
      max-request-size: 10MB
      resolve-lazily: false
    converters: 
      preferred-json-mapper: jackson
    encoding:
      enabled: true
      charset: UTF-8
  jackson: 
    date-format: yyyy-MM-dd HH:mm:ss
    timeZone: GMT+08:00
  messages: 
    encoding: UTF-8
  mvc: 
    async: 
      request-timeout: 30000
    date-format: yyyy-MM-dd HH:mm:ss
  transaction: 
    # Default transaction timeout in seconds.
    default-timeout: 600
    rollback-on-commit-failure: true
  datasource:
    # 使用c3p0数据库连接池
    type: com.mchange.v2.c3p0.ComboPooledDataSource

server: 
  port: ${SERVER_PORT:10008}
  display-name: ${TENANT_GROUP:vanke-scpg-}pluto
  connection-timeout: 12000
  context-path: /
  server-header: 
  servlet-path: /
  tomcat: 
    async-timeout: 60000
    max-connections: ${SERVER.TOMCAT.MAX-CONNECTIONS:1024}
    max-threads: ${SERVER.TOMCAT.MAX-THREADS:8}
    accept-count: ${SERVER.TOMCAT.ACCEPT-COUNT:1024}
    min-spare-threads: ${SERVER.TOMCAT.MIN-SPARE-THREADS:2}
    acceptor-thread-count: ${SERVER.TOMCAT.ACCEPTOR-THREAD-COUNT:8}
    max-http-post-size: 10000000

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: ${REGISTER_CENTER_DEFAULT_SERVICE_URL:http://qfregister1.intra.sit.ffan.com/eureka/}

# Web Async
# effective是高效异步任务管理池
async: 
  effective: 
    maxPoolSize: 256
    keepAliveSeconds: 60
    queueCapacity: 2048
    corePoolSize: 128
    threadNamePrefix: EffectiveTask-
    allowCoreThreadTimeOut: true
    waitForTasksToCompleteOnShutdown: true
  # common是普通异步任务管理池
  common: 
    maxPoolSize: 32
    keepAliveSeconds: 16
    queueCapacity: 128
    corePoolSize: 8
    threadNamePrefix: CommonTask-
    allowCoreThreadTimeOut: true
    waitForTasksToCompleteOnShutdown: true

# 自定义REDIS配置
redis: 
  hostName: ${REDIS.HOST:localhost}
  #password: xxx
  port: ${REDIS.PORT:6379}
  timeout: ${REDIS.TIMEOUT:30000}
  #useSsl: false
  #dbIndex: 0
  usePool: true
  # redis pool配置
  pool: 
    maxTotal: ${REDIS.POOL.MAX_TOTAL:32}
    maxIdle: ${REDIS.POOL.MAX_IDLE:16}
    minIdle: ${REDIS.POOL.MIN_IDLE:8}
    # 空闲链接逐出配置
    # 逐出连接的最小空闲时间 1800000毫秒(30分钟)
    timeBetweenEvictionRunsMillis: 300000
    # 逐出扫描的时间间隔(毫秒) 如果为负数,则不运行逐出线程, 默认-1
    minEvictableIdleTimeMillis: 1800000
    # 每次逐出检查时 逐出的最大数目
    numTestsPerEvictionRun: 3

# 数据源配置
datasource:
  # Master数据源配置
  master:
    driverClass: com.mysql.jdbc.Driver
    jdbcUrl: jdbc:mysql://${C3P0.HOST:localhost}:${C3P0.PORT:3306}/${C3P0.DATABASE:d}?useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true&failOverReadOnly=false
    user: ${C3P0.USER:root}
    password: ${C3P0.PASSWORD:}
    minPoolSize: ${C3P0.MINPOOLSIZE:16}
    maxPoolSize: ${C3P0.MAXPOOLSIZE:32}
    maxIdleTime: 1800000
    acquireIncrement: ${C3P0.ACQUIREINCREMENT:2}
    maxStatements: 0
    initialPoolSize: ${C3P0.INITIALPOOLSIZE:16}
    idleConnectionTestPeriod: 60
    acquireRetryAttempts: 5
    acquireRetryDelay: 1000
    breakAfterAcquireFailure: false
    testConnectionOnCheckin: true
    testConnectionOnCheckout: false
    preferredTestQuery: SELECT 1 FROM DUAL

# mybatis配置
mybatis:
  config_location: /bean/mybatis/mybatis_config.xml
  mapper_locations: /bean/mybatis/mapping/*.xml
#  type-aliases-package: com.wanda.hawk.domain.dao.po
#  # type-handlers-package: com.example.typehandler
  executorType: REUSE

## Perform Framework
#performframework:
#  # 单位ms
#  threshold: 50
#  # 入口配置
#  entrance:
#    # proxyTargetClass: false
#    interceptorNames: interceptorChain
#    # 参与接口调用性能监控的类或者接口列表(支持一个*通配符),多个用英文逗号分隔
#    beanNames: '*Service'
#    # 在beanNames中不参与接口调用性能监控的类或者接口列表(支持一个*通配符)
#    beanNamesExclude: mvcConversionService
#  # 调用链配置
#  chain:
#    # proxyTargetClass: false
#    interceptorNames: performanceInstrumentInterceptor
#    # 参与接口调用性能监控的类或者接口列表(支持一个*通配符),多个用英文逗号分隔
#    beanNames: '*Domain,*Repository,*DAO'
#    # 在beanNames中不参与接口调用性能监控的类或者接口列表(支持一个*通配符)
#    beanNamesExclude: mvcConversionService